# Generated by Django 5.2.4 on 2025-08-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
