# Generated by Django 5.2.4 on 2025-07-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0002_alter_user_email_alter_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
