# Generated by Django 5.2.4 on 2025-08-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainForm', '0002_alter_user_managers_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
